In [2]:
pets=['dog','cat','fish','rabbit','cat']
while 'cat' in pets:
    pets.remove('cat')
print(pets)

['dog', 'fish', 'rabbit']


In [6]:
def greet(a):
    print(a)

In [7]:
greet(ji)

NameError: name 'ji' is not defined

In [5]:
greet()

hello


In [9]:
def greet(a):
    print(a)
greet('ji')
greet('hu')
greet('re')

ji
hu
re


In [16]:
def uh(yu,ok=''):
    print(yu,ok)
    print(ok)
uh('avijit','biswas')
uh('Barun')

avijit biswas
biswas
Barun 



In [17]:
print('vijit')

vijit


In [19]:
def uh(yu,ok):
    fn=yu+' '+ok
    return fn
uh('avijit','biswas')


'avijit biswas'

In [22]:
def uh(yu,ok):
    fn=yu+' '+ok
    return fn.title()
uh('avijit','biswas')

'Avijit Biswas'

In [26]:
def gu(names):
    for name in names:
        msg="hello "+name+' !'
        print(msg)
gu(['hannah','ty','margot'])

hello hannah !
hello ty !
hello margot !


In [28]:
def print_models(unprintde,printed):
    while unprintde:
        current_model=unprintde.pop()
        print("printing "+current_model)
        printed.append(current_model)
unprintde=['phone case','pendant','ring']
printed=[]
print_models(unprintde,printed)
print("\nUnprinted:",unprintde)
print("Printed:",printed)

printing ring
printing pendant
printing phone case

Unprinted: []
Printed: ['ring', 'pendant', 'phone case']


In [29]:
def print_models(unprintde,printed):
    while unprintde:
        current_model=unprintde.pop()
        print("printing "+current_model)
        printed.append(current_model)
original=['phone case','pendant','ring']
printed=[]
print_models(original[:],printed)
print("\nOriginal:",original)
print("Printed:",printed)

printing ring
printing pendant
printing phone case

Original: ['phone case', 'pendant', 'ring']
Printed: ['ring', 'pendant', 'phone case']


In [30]:
def make_pizza(size,*toppings):
    print("\nMaking a "+size+" pizza.")
    print("Toppings:")
    for topping in toppings:
        print("-"+topping)
make_pizza('small','pepperoni')
make_pizza('large','bacon bits','pineapple')
make_pizza('medium','mushrooms','peppers','onions','extra cheese')


Making a small pizza.
Toppings:
-pepperoni

Making a large pizza.
Toppings:
-bacon bits
-pineapple

Making a medium pizza.
Toppings:
-mushrooms
-peppers
-onions
-extra cheese


In [2]:
class Car():
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
        
        self.fuel_capacity=15
        self.fuel_level=0
        
    def fill_tank(self):
        self.fuel_level=self.fuel_capacity
        print("Fuel tank is full.")
    def drive(self):
        print("The car is moving.")

In [3]:
my_car=Car('audi','a4','2016')

In [4]:
print(my_car.make)
print(my_car.model)
print(my_car.year)

audi
a4
2016


In [5]:
my_car.fill_tank()
my_car.drive()

Fuel tank is full.
The car is moving.


In [6]:
my_car=Car('audi','a4',2016)
my_old_car=Car('subaru','outback',2013)
my_truck=Car('toyota','tacoma',2010)

In [7]:
print(my_old_car.make)
print(my_old_car.model)
print(my_old_car.year)
print(my_truck.make)
print(my_truck.model)
print(my_truck.year)

subaru
outback
2013
toyota
tacoma
2010


In [8]:
my_new_car=Car('audi','a4',2016)
my_new_car.fuel_level=5

In [9]:
def update_fuel_level(self,new_level):
    if new_level<=self.fuel_capacity:
        self.fuel_level=new_level
    else:
        print("The tank can't hold that much!")

In [10]:
my_string='thisstringisAwesome'

In [11]:
my_string

'thisstringisAwesome'

In [12]:
my_string*2

'thisstringisAwesomethisstringisAwesome'

In [13]:
my_string+'Innit'

'thisstringisAwesomeInnit'

In [14]:
'm' in my_string

True

In [15]:
a='is'
b='nice'
my_list=['my','list',a,b]
my_list2=[[4,5,6,7],[3,4,5,6]]

In [16]:
print(my_list)
print(my_list2)

['my', 'list', 'is', 'nice']
[[4, 5, 6, 7], [3, 4, 5, 6]]


In [17]:
my_list2

[[4, 5, 6, 7], [3, 4, 5, 6]]

In [22]:
my_list.index('list')

1

In [24]:
my_list2.index([4, 5, 6, 7])

0

In [29]:
my_list.count(a)

1

In [32]:
my_list.append('!')

In [33]:
my_list

['my', 'list', 'is', 'nice', '!']

In [34]:
my_list.remove('!')

In [35]:
my_list

['my', 'list', 'is', 'nice']

In [36]:
del my_list[0:1]

In [37]:
my_list

['list', 'is', 'nice']

In [38]:
my_list.reverse()

In [39]:
my_list

['nice', 'is', 'list']

In [40]:
my_list.extend('!')

In [41]:
my_list

['nice', 'is', 'list', '!']

In [42]:
my_list.pop(-1)

'!'

In [43]:
my_list

['nice', 'is', 'list']

In [44]:
my_list.insert(0,'!')

In [45]:
my_list


['!', 'nice', 'is', 'list']

In [46]:
my_list.sort()

In [47]:
my_list

['!', 'is', 'list', 'nice']

In [48]:
import numpy as np
from math import pi

In [49]:
my_list=[1,2,3,4]

In [50]:
my_list

[1, 2, 3, 4]

In [51]:
my_array=np.array(my_list)
my_2darray=np.array([[1,2,3],[4,5,6]])

In [52]:
my_array[1]

2

In [53]:
my_array[0:2]

array([1, 2])

In [54]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
my_2darray>3

array([[False, False, False],
       [ True,  True,  True]])

In [56]:
my_2darray*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [57]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
my_array

array([1, 2, 3, 4])

In [59]:
my_array+np.array([5,6,7,8])

array([ 6,  8, 10, 12])

In [60]:
my_2darray.shape



(2, 3)

In [61]:
np.append(other_array)

NameError: name 'other_array' is not defined

In [62]:
np.insert(my_2darray,1,5)

array([1, 5, 2, 3, 4, 5, 6])

In [63]:
np.std(my_array)

1.118033988749895

In [64]:
np.std(my_2darray)

1.707825127659933